---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/pylint
    rev: "v2.17.4"
    hooks:
      - id: pylint
        name: Check for Linting errors on Python files
        types: [python]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.32.0"
    hooks:
      - id: yamllint
        name: Check for Linting errors on YAML files
        entry: yamllint
        language: python
        types: [file, yaml]
        args: [--strict]

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.11
    hooks:
      - id: pymarkdown
