---
namespace: controlware
name: utils
description: Generic ansible utils like filters or modules
tags: [controlware, utils, tools, filters]
authors:
  - Korte Noack (@kornoa)

version: 1.0.3
license_file: 'LICENSE'

readme: README.md
repository: https://github.com/Controlware-GmbH/ansible-utils
documentation: https://github.com/Controlware-GmbH/ansible-utils
homepage: https://github.com/Controlware-GmbH/ansible-utils
issues: https://github.com/Controlware-GmbH/ansible-utils/issues

dependencies: {}
build_ignore: []
