---
# This workflow will install Python dependencies and run ansible tests

name: Ansible Collection Code Testing

'on':
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install --upgrade -r requirements-dev.txt
      - name: Run pre-commit
        run: |
          pre-commit run --all-files --color always

  ansible-testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install python3.10
        run: |
          apt install python3.10
      - name: Install python3.11
        run: |
          apt install python3.11
      - name: Install ansible-core
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core>=2.9
      - name: Ansible-Test Sanity
        run: |
          cd ansible_collections/controlware/utils/
          ansible-test sanity
          ansible-test units
