---
# This workflow will install Python dependencies and run ansible tests

name: Ansible Collection Code Testing

'on':
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install --upgrade pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --all-files --color always

  ansible-testing:
    runs-on: ubuntu-22.04
    needs: [pre_commit]
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        include:
          - python_version: "3.7"
            ansible-core_version: ["2.11"]
          - python_version: "3.8"
            ansible-core_version: ["2.11", "2.12", "2.13"]
          - python_version: "3.9"
            ansible-core_version: ["2.11", "2.12", "2.13", "2.14", "2.15"]
          - python_version: "3.10"
            ansible-core_version: ["2.11", "2.12", "2.13", "2.14", "2.15"]
          - python_version: "3.11"
            ansible-core_version: ["2.11", "2.12", "2.13", "2.14", "2.15"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install requirements
        run: |
          pip install --upgrade ansible-core${{ matrix.ansible-core_version }}
          pip install --upgrade -r \
          requirements-ansible-test_${{ matrix.ansible-core_version }}.txt
      - name: Ansible-Test Sanity
        run: |
          cd ansible_collections/controlware/utils/
          ansible-test sanity
      - name: Ansible-Test Units
        run: |
          cd ansible_collections/controlware/utils/
          ansible-test units
